---
title: "Open Source"
---


# R 

Within *R* I collaborate with developers in several packages, as well as participating in their respective online forums

* [lavaan](https://www.lavaan.ugent.be/): is developed to provide useRs, researchers and teachers a free open-source, but commercial-quality package for latent variable modeling. You can use *lavaan* to estimate a large variety of multivariate statistical models, including path analysis, confirmatory factor analysis, structural equation modeling and growth curve models. 
* [blavaan](http://ecmerkle.github.io/blavaan/): is a free, open source R package for Bayesian latent variable analysis. It relies on JAGS and Stan to estimate models via MCMC. Building on top of *lavaan* functionality for Bayesian models.
* [semTools](https://github.com/simsem/semTools/wiki): Provides tools for structural equation modeling, many of which extend the *lavaan* package
* [tidySEM](https://cjvanlissa.github.io/tidySEM/): provides a ‘tidy’ workflow for conducting, reporting, and plotting structural equation modeling analyses. It does not perform model estimation, but instead allows users to estimate models in a software-agnostic way, using either the free open source R packages *lavaan* or *OpenMx*, or the commercial closed-source program *Mplus*.

# Stan

Among the variety of general Bayesian software, I mostly work with [Stan](https://mc-stan.org/), to develop and test models such as SEM, IRT, and LCA. As well as being an active member in their [open forum](https://discourse.mc-stan.org/). 


