---
title: "Publications"
---

# Methodological

1.   **Garnier-Villarreal, M.,** & Johnson, D. K. (2025). Bayesian multivariate longitudinal piecewise regression: Detecting early onset of cognitive decline. *Journal of Behavioral Medicine*. <https://doi.org/10.1007/s10865-025-00616-4>
2.  Pankowska, P., Oberski, D., **Garnier-Villarreal, M.,** & Pavlopoulos, D. (2025). The effect of measurement error on clustering. *Quality & Quantity*. <https://doi.org/10.1007/s11135-025-02177-9>
3.  Liang, X., Li, J., **Garnier-Villarreal, M.,** & Zhang, J. (2025). Comparing Frequentist and Bayesian Methods for Factorial Invariance with Latent Distribution Heterogeneity. Behavioral Sciences, 15(4), 1–21. <https://doi.org/10.3390/bs15040482>
4.  **Garnier-Villarreal, M.**, & Jorgensen, T. D. (2024). Evaluating Local Model Misspecification with Modification Indices in Bayesian Structural Equation Modeling. Structural Equation Modeling: A Multidisciplinary Journal, 1–15. <https://doi.org/10.1080/10705511.2024.2413128>
5.  Merkle, E. C., Ariyo, O., Winter, S. D., & **Garnier-Villarreal, M.** (2023). Opaque prior distributions in Bayesian latent variable models. Methodology, 19(3), 228--255. <https://doi.org/10.5964/meth.11167>
6.  Van Lissa, C. J., **Garnier-Villarreal, M.**, & Anadria, D. (2023). Recommended Practices in Latent Class Analysis Using the Open-Source R-Package tidySEM. Structural Equation Modeling: A Multidisciplinary Journal, 1--9. <https://doi.org/10.1080/10705511.2023.2250920>
7.  Jorgensen, T.D., **Garnier-Villarreal, M.** (2023). Limited Utility of Small-Variance Priors to Detect Local Misspecification in Bayesian Structural Equation Models. In: Wiberg, M., Molenaar, D., González, J., Kim, JS., Hwang, H. (eds) Quantitative Psychology. IMPS 2022. Springer Proceedings in Mathematics & Statistics, vol 422. Springer, Cham. https://doi.org/10.1007/978-3-031-27781-8_8
8.  **Garnier-Villarreal, M.** & Little, T. D. (in press). Bayesian Longitudinal Structural Equation Modeling (Chapter 13). In T. D. Little (author), Longitudinal Structural Equation Modeling (2nd Edition). New York, NY: Guildford press.
9.  **Garnier-Villarreal, M.**; Merkle, E.C.; Magnus, B.E. (2021) Between-Item Multidimensional IRT: How Far Can the Estimation Methods Go? Psych, 3, 404--421. <https://doi.org/10.3390/psych3030029>
10. Magnus, B. E., & **Garnier-Villarreal, M.** (2021). A multidimensional zero-inflated graded response model for ordinal symptom data. Psychological Methods. <https://doi.org/10.1037/met0000395> <https://osf.io/hvkfn/>
11. Smits, N., Öğreden, O., **Garnier-Villarreal, M.**, Terwee, C. B., & Chalmers, R. P. (2020). A study of alternative approaches to non-normal latent trait distributions in item response theory models used for health outcome measurement. Statistical Methods in Medical Research. <https://doi.org/10.1177/0962280220907625>
12. **Garnier-Villarreal, M.**, & Jorgensen, T. D. (2020). Adapting Fit Indices for Bayesian Structural Equation Modeling: Comparison to Maximum Likelihood. Psychological Methods, 25(1), 46--70. <https://doi.org/dx.doi.org/10.1037/met0000224>
13. Jorgensen T.D., **Garnier-Villarreal M.**, Pornprasermanit S., Lee J. (2019) Small-Variance Priors Can Prevent Detecting Important Misspecifications in Bayesian Confirmatory Factor Analysis. In: Wiberg M., Culpepper S., Janssen R., González J., Molenaar D. (eds) Quantitative Psychology. IMPS 2017. Springer Proceedings in Mathematics & Statistics, vol 265. Springer, Cham. <https://doi.org/10.1007/978-3-030-01310-3_23>
14. Chen, P.-Y., Wu, W., **Garnier-Villarreal, M.**, Kite, B. A., & Jia, F. (2019). Testing Measurement Invariance with Ordinal Missing Data: A Comparison of Estimators and Missing Data Techniques. Multivariate Behavioral Research, 1--15. <https://doi.org/10.1080/00273171.2019.1608799>
15. **Garnier-Villarreal, M.**, Rhemtulla, M., & Little, T. D. (2014). Two-method planned missing designs for longitudinal research. International Journal of Behavioral Development, 38(5), 411--422. <doi:10.1177/0165025414542711>

# Applied

1.  Bouwhuis, S., Pauls, C., **Garnier-Villarreal, M.,** & Pavlopoulos, D. (2026). The interplay between job demands & resources and mental health: A novel approach using hidden Markov models. *Journal of Behavioral Medicine*. <https://doi.org/10.1007/s10865-025-00626-2>

2.  Frenn, M., Salzman, N., Lam, V., Holtz, M., Moosreiner, A., **Garnier-Villarreal, M.,** & Singh, M. (2025). Childhood Obesity Body Mass Index and Gut Microbiome: A Cluster Randomized Controlled Pilot Feasibility Study. *Childhood Obesity*, 1–8. <https://doi.org/10.1089/chi.2024.0344>

3.  Chowdhury, A., van der Horst, M., Pavlopoulos, D., & **Garnier-Villarreal, M.** (2025). Cliff-edge or atypical retirement? Exploring retirement trajectories of post-war baby boomers in The Netherlands. *Ageing and Society*, 1–24. <https://doi.org/10.1017/S0144686X25000029>

4.  Matetovici, M., Spruit, A., Colonnesi, C., **Garnier‐Villarreal, M.,** & Noom, M. (2025). Parent and child gender effects in the relationship between attachment and both internalizing and externalizing problems of children between 2 and 5 years old: A dyadic perspective. *Infant Mental Health Journal: Infancy and Early Childhood*, 46(4), 424–444. <https://doi.org/10.1002/imhj.70002>

5.  Varriale, R., Filipponi, D., **Garnier-Villarreal, M.**, Pavlopoulos, D., & Stoel, R. D. (2024). New approaches for non-standard employment statistics using multi-source data. The Dutch and Italian experience. In Book of *Short Papers 2nd Italian Conference on Economic Statistics* (ICES 2024) : Statistical Analysis of Complex Economic Data: Recent Developments and Applications (pp. 166-169). Casa Editrice Bonechi.

6.  Filipponi, D., **Garnier-Villarreal, M.,** Loriga, S., Pavlopoulos, D., Stoel, R. D., & Varriale, R. (2024). Measurement of contract type from multi-source data. Preliminary results from the Dutch and Italian experience. In *2nd Workshop on Methodologies for Official Statistics. Proceedings* (pp. 31-44). Italian National Institute of Statistics (Istat).

7.  Bouwhuis, S., Pavlopoulos, D., **Garnier-Villarreal, M.**, & Eberlein, L. (2024). Mixture hidden markov modellen in sociaal-wetenschappelijk onderzoek. *Belgisch Tijdschrift Voor Sociale Zekerheid*, 65(3), 425-439.

8.  Bouwhuis, S., Pavlopoulos, D., **Garnier-Villarreal, M.,** & Eberlein, L. (2024). Les mixture hidden markov models (modèles de markov cachés à effets mixtes) dans la recherche en sciences sociales. Revue belge de sècuritè sociale, 65(3), 429-443.

9.  Johnson, N. L., Bekhet, A. K., Zint, E., Wang, J., Pena, S., Van Hecke, A., **Garnier-Villarreal, M.**, & Ng, A. (2024). Correlations of Physical and Psychological Health in Parents of Individuals With Autism Spectrum Disorder. *Western Journal of Nursing Research*, 46(7), 532–540. <https://doi.org/10.1177/01939459241253221>

10. Varriale, R., Filipponi, D., **Garnier-Villarreal, M.,** & Pavlopoulos, D. . (2024). How "real" is mobility from temporary to permanent employment in italy? A focus on measurement error. *Statistica Applicata - Italian Journal of Applied Statistics*. <https://doi.org/10.26398/IJAS.272>

11. Bouwhuis, S., Hellendoorn, M., Pavlopoulos, D., **Garnier-Villarreal, M.,** & Smits, W. (2024). Strategieën van Nederlandse werkgevers voor het gebruik van flexcontracten en de relatie met loopbanen van flexwerkers. *Tijdschrift voor Arbeidsvraagstukken*, 40(1), 65–90. <https://doi.org/10.5117/TVA2024.1.005.BOUW>

12. Eberlein, L., Pavlopoulos, D., & **Garnier-Villarreal, M.** (2024). Starting flexible, always flexible? The relation of early temporary employment and young workers employment trajectories in the Netherlands. *Research in Social Stratification and Mobility*, *89*, 100861. <https://doi.org/10.1016/j.rssm.2023.100861>

13. Pavlopoulos, D., **Garnier-Villarreal, M.**, & Varriale, R. (2023). Patterns of flexible employment careers. Does measurement error matter? In F. M. Chelli, M. Ciommi, S. Ingrassia, F. Mariani, & M. C. Recchioni (Eds.), *SIS 2023 (SEAS IN): Book of the short papers* (pp. 985-990). Pearson.

14. Bouwhuis, S., Pavlopoulos, D., **Garnier‐Villarreal, M.,** & Smits, W. (2023). Ad hoc decisions as latent strategies: How do firms use nonstandard employment contracts? *Industrial Relations Journal*,1–19. <https://doi.org/10.1111/irj.12416>

15. Wahl, C. A., **Garnier-Villarreal, M.**, & Meyer, B. B. (2023). Development of the assessment of recovery activities for athletes. *International Journal of Sport and Exercise Psychology*, 22(4), 825–844. <https://doi.org/10.1080/1612197X.2023.2168727>

16. Hlebichuk, J. L., Gretebeck, R. J., **Garnier-Villarreal, M.,** Piacentine, L. B., Singh, M., & Gretebeck, K. A. (2023). Physical Activity, Inflammation, and Physical Function in Older Adults: Results From the Health & Retirement Study. *Biological Research For Nursing*, 25(1), 24–32. <https://doi.org/10.1177/10998004221111217>

17. Haglund, K., King, A. L., Bekhet, A. K., **Garnier-Villarreal, M.,** Olson, K., Atshan, R., Ortiz, A., Santos, J. de los, & Belknap, R. A. (2023). Learning a Healthy Rhythm: An Intervention to Increase Children’s Resources for Stress Management. *Western Journal of Nursing Research*, 45(1), 46–54. <https://doi.org/10.1177/01939459221099362>  

18. Valdez, C. E., Stevens, T., **Garnier-Villarreal, M.,** & Shumway, M. (2022). Using Bayesian methods to clarify the role of trauma-related cognitions on the course of posttraumatic stress in nonspecific trauma-focused therapy. *Psychological Trauma: Theory, Research, Practice, and Policy.* <https://doi.org/10.1037/tra0001280>

19. Lavoie, J.A., Schindler, C., **Garnier-Villarreal, M**., Bagli, SP, McCarthy, D.O., Goday, P.S. (2022) Nasogastric bridles are associated with improved tube-related outcomes in children. *J Parenter Enteral Nutr*; 1- 10. <https://doi.org/10.1002/jpen.2409>

20. Burns, J., Basken, A., Acosta, R., **Garnier-Villarreal, M.,** Kulkarni, A., & Hayes, D. (2022). Identification of research priorities in CHD: Empowering patients and families through participation in the development of formal research agendas. *Cardiology in the Young*, 1-6. <https://doi.org/10.1017/S104795112200066X>

21. Hanson, L., VandeVusse, L., Malloy, E., **Garnier-Villarreal, M.,** Watson, L., Fial, A., Forgie, M., Nardini, K., & Safdar, N. (2022). Probiotic interventions to reduce antepartum Group B streptococcus colonization: A systematic review and meta-analysis. *Midwifery*, 105, 103208. <https://doi.org/10.1016/j.midw.2021.103208>

22. Grau, P. P., Melchert, T. P., **Garnier-Villarreal, M.,** Knobloch-Fedders, L. M., & Wetterneck, C. T. (2021). Change in Self-compassion, Psychological Inflexibility, and Interpersonal Courage in Intensive PTSD Treatment: A Latent Growth Curve Analysis. *Mindfulness*. <https://doi.org/10.1007/s12671-021-01759-6>

23. **Garnier-Villarreal, M.,** Pinto, D., Mummidisetty, C. K., Jayaraman, A., Tefertiller, C., Charlifue, S., Taylor, H. B., Chang, S.-H., McCombs, N., Furbish, C. L., Field-Fote, E. C., & Heinemann, A. W. (2021). Predicting Duration of Outpatient Physical Therapy Episodes for Individuals with Spinal Cord Injury Based on Locomotor Training Strategy. *Archives of Physical Medicine and Rehabilitation*, 1–11**.** <https://doi.org/10.1016/j.apmr.2021.07.815>

24. Clayton-Jones, D., Ong. L.Z., **Garnier-Villarreal, M.**, Vick, L., Sawdy, R., George Dalmida, S. & Haglund, K. (2021). Complementary and alternative medicine mind-body approaches used among racially and ethnically diverse adolescents, *Journal of Pediatric Nursing*, 61, 254-259. <https://doi.org/10.1016/j.pedn.2021.07.009>  

25. Haglund, K., Ortiz, A., Santos, J. D. L., **Garnier-Villarreal, M.**, & Belknap, R. A. (2021). An Engaged Community-Academic Partnership to Promote Positive Youth Development. *Journal of Community Engagement and Scholarship*, 13(2), 11. <https://doi.org/10.54656/LNWP6978>.

26. Grau, P.P., Larsen, S.E., Lancaster, S.L., **Garnier‐Villarreal, M**. & Wetterneck, C.T. (2021), Change in Event Centrality and Posttraumatic Stress Disorder Symptoms During Intensive Treatment. *Journal of Traumatic Stress*, 34, 116-123. <https://doi.org/10.1002/jts.22541>

27. Edwards, L.M., Le, H.M., & **Garnier-Villarreal, M.** (2021).A systematic review and meta-analysis of risk factors for postpartum depression among Latinas. *Maternal and Child Health Journal.* <https://doi.org/10.1007/s10995-020-03104-0>

28. Johnson, N. L., Bekhet, A. K., Karenke, T., & **Garnier-Villarreal, M.** (2021). Swim Program Pilot for Children with Autism: Impact on Behaviors and Health. *Western Journal of Nursing Research*, 43(4), 356–363. <https://doi.org/10.1177/0193945920948867>

29. Groom, K. K., Frenn, M., Breakwell, S., Melchert, T., & **Garnier-Villarreal, M.** (2021). Comparing Interprofessional Socialization in Mixed-Discipline and Nursing Student-Only Cohorts. Nurse educator, 46(6), 376–380. <https://doi.org/10.1097/NNE.0000000000000985>

30. Jerofke-Owen, T. A., & **Garnier-Villarreal, M**. (2020). Development and Psychometric Analysis of the Patient Preferences for Engagement Tool. Nursing research, 69(4), 289–298. <https://doi.org/10.1097/NNR.0000000000000423>  

31. Frenn M, Kaugars A, Garcia J, **Garnier-Villarreal M.** (2020) Child Body Fat and Body Mass Index: Which Determinants are Most Important? *Western Journal of Nursing Research*. 42(8):593-602. [https://doi:10.1177/0193945919879960](https://doi:10.1177/0193945919879960)

32. Jerofke‐Owen, T., **Garnier‐Villarreal, M.**, Fial, A., & Tobiano, G. (2020). Systematic review of psychometric properties of instruments measuring patient preferences for engagement in health care. *Journal of Advanced Nursing*, <https://doi.org/10.1111/jan.14402>

33. Johnson, N. L., Lerret, S., Klingbeil, C. G., Polfuss, M., Gibson, C., Gralton, K., **Garnier-Villarreal, M.**, Ahamed, S. I., Riddhiman, A., Unteutsch, R., Pawela, L., White-Traut, R., Sawin, K., & Weiss, M. (2020). Engaging parents in education for discharge (ePED): Evaluating the reach, adoption & implementation of an innovative discharge teaching method. *Journal of Pediatric Nursing*, *54*, 42–49. <https://doi.org/10.1016/j.pedn.2020.05.022>   

34. Lerret, S. M., Johnson, N. L., Polfuss, M., Weiss, M., Gralton, K., Klingbeil, C. G., Gibson, C., **Garnier-Villarreal, M.**, Ahamed, S. I., Adib, R., Unteutsch, R., Pawela, L., White-Traut, R., & Sawin, K. (2020). Using the engaging parents in education for discharge (ePED) iPad application to improve parent discharge experience. *Journal of Pediatric Nursing*, *52*, 41–48. <https://doi.org/10.1016/j.pedn.2020.02.041>

35. Pinto, D., **Garnier-Villarreal, M.**, Barbas, J., Chang, S.-H., Charlifue, S., Field-Fote, E., Furbish, C., Tefertiller, C., Mummidisetty, C. K., Taylor, H., Jayaraman, A., & Heinemann, A. W. (2020)*.* Budget impact analysis of robotic exoskeleton use for locomotor training following spinal cord injury in four SCI Model Systems. *Journal of NeuroEngineering and Rehabilitation, 17(1), 4.* <https://doi.org/10.1186/s12984-019-0639-0>

36. Tyacke, M., Guttormson, J. L., **Garnier-Villarreal, M.**, Schroeter, K., & Peltier, W. (2019) Advance Directives and Intensity of Care Delivered to Hospitalized Older Adults at the End-Of-Life. *Heart and Lung.* https://doi: 10.1016/j.hrtlng.2019.08.018.

37. Cleland, B. T., Papanek, P., Ingraham, B. A., Harkins, A., **Garnier-Villarreal, M.**, Woo, D., … V. Ng, A. (2019). Determinants of low bone mineral density in people with multiple sclerosis: Role of physical activity. *Multiple Sclerosis and Related Disorders*, 101864. <https://doi.org/10.1016/j.msard.2019.101864>

38. Grau, P., **Garnier-Villarreal, M.,** & Wettemeck, C. (2019). An Analysis of the Latent Factor Structure of the PCL-5 in a PTSD Partial Hospitalization Program. *Traumatology.* <https://doi.org/10.1037/trm0000200>

39. King, A. L., **Garnier-Villarreal, M.**, Simanek, A. M., & Johnson, N. L. (2019). Testing allostatic load factor structures among adolescents: A structural equation modeling approach. *American Journal of Human Biology*, 232–242. <https://doi.org/10.1002/ajhb.23242>

40. Woda, A., Dreifuerst, K., & **Garnier-Villarreal, M**. (2019). The Impact of Supplemented Simulation on Newly Licensed Registered Nurses. *Journal of Clinical Simulation in Nursing.* <http://doi.org/10.1016/j.ecns.2018.12.002>

41. Woda, A., Hansen, J., Dreifuerst, K. T., Anderson, P., Hardy, T., & **Garnier-Villarreal, M.** (2019). The Impact of Simulation on Knowledge and Performance Gain Regarding Diabetic Patient Care. *Clinical Simulation in Nursing*, *34*, 16–21. <https://doi.org/10.1016/j.ecns.2019.05.001>

42. Hardy, T. M., **Garnier-Villarreal, M.**, Ohlendorf, J. M., & McCarthy, D. O. (2019). Chronic Stress and Ovarian Function in Female Childhood Cancer Survivors. *Oncology Nursing Forum*, *46*(3), 75–85. <https://doi.org/10.1188/19.ONF.E75-E85>

43. Ohlendorf, J. M., Robinson, K., & **Garnier-Villarreal, M.** (2019). The impact of maternal BMI, gestational weight gain, and breastfeeding on early childhood weight: Analysis of a statewide WIC dataset. *Preventive Medicine*, *118*, 210–215. <https://doi.org/10.1016/j.ypmed.2018.11.001>

44. Ruekert Kobiske, K., Bekhet, A. K., **Garnier-Villarreal, M.**, & Frenn, M. (2018). Predeath Grief, Resourcefulness, and Perceived Stress Among Caregivers of Partners With Young-Onset Dementia. *Western Journal of Nursing Research*, 1–17. <https://doi.org/10.1177/0193945918806689>

45. Bekhet, A. K., & **Garnier-Villarreal, M**. (2018). Factor Structure and Psychometric Properties of Cognitive-Behavioral Scales in Caregivers of Persons with Dementia. *International Journal of Psychology and Psychoanalysis*, *4*(2). <https://doi.org/10.23937/2572-4037.1510035>

46. Bekhet, A. K., & **Garnier-Villarreal, M.** (2018). Depression, positive thinking, personal and social resourcefulness among caregivers of persons with autism spectrum disorders. *Archives of Psychiatric Nursing*, *32*(6), 823–827. <https://doi.org/10.1016/j.apnu.2018.06.006>

47. Valdivieso-Mora, E., Ivanisevic, M., Shaw, L. A., **Garnier-Villarreal, M.**, Green, Z. D., Salazar-Villanea, M., … Johnson, D. K. (2018). Health-Related Quality of Life of Older Adults in Costa Rica as Measured by the Short-Form-36 Health Survey. *Gerontology and Geriatric Medicine*, *4*, 233372141878281. <https://doi.org/10.1177/2333721418782812>

48. Watts, A., **Garnier-Villarreal, M.**, & Gardiner, P. (2018). Measurement of Sitting Time in Older Adults With and Without Alzheimer’s Disease. Journal for the Measurement of Physical Behaviour, 1(2), 70–78. <https://doi.org/10.1123/jmpb.2018-0002>

49. Woda, A., Schnable, T., Alt-Gehrman, P., Bratt, M., & **Garnier-Villarreal, M.** (2018). Innovation in clinical course delivery and impact on students’ clinical decision making and competence**.** *Nursing Education Perspectives.* <https://doi.org/10.1097/01.NEP.0000000000000406>

50. Hardy, T. M., **Garnier-Villarreal, M.**, McCarthy, D. O., Anderson, R. A., & Reynolds, R. M. (2018). Exploring the Ovarian Reserve Within Health Parameters: A Latent Class Analysis. *Western Journal of Nursing Research*, 1–16. <https://doi.org/10.1177/0193945918792303>

51. Robinson, K., **Garnier-Villarreal, M.**, & Hanson, L. (2018). Effectiveness of CenteringPregnancy on Breast-Feeding Initiation Among African Americans: A Systematic Review and Meta-analysis. The Journal of Perinatal & Neonatal Nursing, 1. <https://doi.org/10.1097/JPN.0000000000000307>

52. Matel-Anderson, D. M., Bekhet, A. K., & **Garnier-Villarreal, M.** (2018). Mediating Effects of Positive Thinking and Social Supposrt on Suicide Resilience. *Western Journal of Nursing Research*. <https://doi.org/10.1177/0193945918757988>

53. Sebern, M. D., Sulemanjee, N., Sebern, M. J., **Garnier-Villarreal, M.**, & Whitlatch, C. J. (2017)*.* Does an intervention designed to improve self-management, social support and awareness of palliative-care address needs of persons with heart failure, family caregivers and clinicians? *Journal of Clinical Nursing.* <https://doi.org/10.1111/jocn.14115>

54. Bekhet, A. K., & **Garnier-Villarreal, M.** (2017). The Positive Thinking Skills Scale: A screening measure for early identification of depressive thoughts. *Applied Nursing Research*, 38, 5–8. <https://doi.org/10.1016/j.apnr.2017.08.004>

55. Harris, M. A., Donnellan, M. B., Guo, J., McAdams, D. P., **Garnier-Villarreal, M.**, & Trzesniewski, K. H. (2017). Parental Co-Construction of 5- to 13-Year-Olds’ Global Self-Esteem Through Reminiscing About Past Events. *Child Development*, 88(6), 1810–1822. <https://doi.org/10.1111/cdev.12944>

56. Shogren, K. A., **Garnier-Villarreal, M**., Lang, K., & Seo, H. (2017). Mediating Role of Self-Determination Constructs in Explaining the Relationship Between School Factors and Postschool Outcomes. *Exceptional Children*, *83*(2), 165–180. <https://doi.org/10.1177/0014402916660089>

57. Valdivieso-Mora, E., Peet, C. L., **Garnier-Villarreal, M.**, Salazar-Villanea, M., & Johnson, D. K. (2016). A Systematic Review of the Relationship between Familism and Mental Health Outcomes in Latino Population. *Frontiers in Psychology, 7*. <https://doi.org/10.3389/fpsyg.2016.01632>

58. Salazar-Villanea, M., Liebmann, E., **Garnier-Villarreal, M**., Montenegro-Montenegro, E., & Johnson, D. K. (2015). Depressive Symptoms Affect Working Memory in Healthy Older Adult Hispanics. *Journal of Depression and Anxiety, 04(04).* <http://doi.org/10.4172/2167-1044.1000204>

59. Johnson, D. K., Langford, Z., **Garnier-Villarreal, M.**, Morris, J. C., & Galvin, J. E. (2016). Onset of Mild Cognitive Impairment in Parkinson Disease: *Alzheimer Disease & Associated Disorders*, *30*(2), 127–133. <https://doi.org/10.1097/WAD.0000000000000088>

60. Shogren, K. A., **Garnier-Villarreal, M**., Dowsett, C., & Little, T. D. (2014). Exploring Student, Family, and School Predictors of Self-Determination Using NLTS2 Data. *Career Development and Transition for Exceptional Individuals*. <doi:10.1177/2165143414546685>

61. Shogren, K. A., Kennedy, W., Dowsett, C**., Garnier-Villarreal, M**., & Little, T. D. (2014). Exploring Essential Characteristics of Self-Determination for Diverse Students Using Data From NLTS2. *Career Development and Transition for Exceptional Individuals*, 37(3), 168–176. <http://doi.org/10.1177/2165143413486927>

62. Shogren, K. A., & **Garnier-Villarreal, M**. (2015). Developing student, family, and school constructs from NTLS2 data. *The Journal of Special Education*, 49(2), 89–103. <http://doi.org/10.1177/0022466913513336>

63. **Garnier-Villarreal, M.**, & Conejo, L. D. (2014). Go/No-Go task. In T. Castelain & B. Marín (Eds.), *Experimental Psychology: Foundations and Experimental Protocols for studying cognitive processes* (pp. 87–99). San Jose, Costa Rica: Universidad de Costa Rica Press.

64. **Garnier-Villarreal, M**, Dinartes Bogantes, A. (2008) "Methodological Guide for the use of compact disc collection: 'Truth, justice and reparation', in the book: 'Latin American Experience, meeting victims'. " American Institute of Human Rights (IIHR). San José, Costa Rica
